<a href="https://colab.research.google.com/github/sharmasimran/tensorflow_learnings/blob/master/Untitled0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install tensorflow-gpu==1.13.1


     |████████████████████████████████| 345.2MB 40kB/s 
     |████████████████████████████████| 3.2MB 51.5MB/s 
     |████████████████████████████████| 368kB 51.0MB/s 
ERROR: tensorflow 2.2.0 has requirement tensorboard<2.3.0,>=2.2.0, but you'll have tensorboard 1.13.1 which is incompatible.
ERROR: tensorflow 2.2.0 has requirement tensorflow-estimator<2.3.0,>=2.2.0, but you'll have tensorflow-estimator 1.13.0 which is incompatible.
  Found existing installation: tensorboard 2.2.2
    Uninstalling tensorboard-2.2.2:
      Successfully uninstalled tensorboard-2.2.2
  Found existing installation: tensorflow-estimator 2.2.0
    Uninstalling tensorflow-estimator-2.2.0:
      Successfully uninstalled tensorflow-estimator-2.2.0


In [ ]:
import tensorflow as tf


/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/dtypes.py:526: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/dtypes.py:527: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/dtypes.py:528: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/dtypes.py:529: FutureWarning: Passing (type, 1) or 

In [ ]:
tf.__version__

'1.13.1'

In [1]:
!pip install tensorflow-gpu==2.0.0-alpha0

     |████████████████████████████████| 332.1MB 25kB/s 
     |████████████████████████████████| 419kB 46.1MB/s 
     |████████████████████████████████| 3.0MB 44.4MB/s 


In [7]:
!pip uninstall -y tensorflow


Uninstalling tensorflow-2.2.0:
  Successfully uninstalled tensorflow-2.2.0


In [8]:
!pip install tensorflow


     |████████████████████████████████| 516.2MB 25kB/s 


In [2]:
import tensorflow as tf


In [3]:
tf.__version__

'2.2.0'

In [4]:
tfconst= tf.constant([[23,4],[32,51]])

In [5]:
tfconst

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[23,  4],
       [32, 51]], dtype=int32)>

In [6]:
tfconst.shape

TensorShape([2, 2])

In [7]:
tfconst.numpy()

array([[23,  4],
       [32, 51]], dtype=int32)

In [9]:
import numpy as np


In [10]:
numpy_tensor= np.array([[23,8],[67,3]])

In [11]:
numpy_tensor

array([[23,  8],
       [67,  3]])

In [12]:
tensor_from_numpy= tf.constant(numpy_tensor)

In [13]:
tensor_from_numpy

<tf.Tensor: shape=(2, 2), dtype=int64, numpy=
array([[23,  8],
       [67,  3]])>

In [14]:
tfvar= tf.Variable([[23,89],[5,78]])

In [15]:
tfvar

<tf.Variable 'Variable:0' shape=(2, 2) dtype=int32, numpy=
array([[23, 89],
       [ 5, 78]], dtype=int32)>

In [17]:
tfvar.numpy()

array([[23, 89],
       [ 5, 78]], dtype=int32)

In [18]:
tfconst +2

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[25,  6],
       [34, 53]], dtype=int32)>

In [19]:
tfconst

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[23,  4],
       [32, 51]], dtype=int32)>

In [20]:
tfconst*5

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[115,  20],
       [160, 255]], dtype=int32)>

In [21]:
np.square(tfconst)

array([[ 529,   16],
       [1024, 2601]], dtype=int32)

In [22]:
np.sqrt(tfconst)

array([[4.79583152, 2.        ],
       [5.65685425, 7.14142843]])

In [24]:
tfstring =tf.constant("Tensorflow 2.0")

In [25]:
tfstring

<tf.Tensor: shape=(), dtype=string, numpy=b'Tensorflow 2.0'>

In [27]:
tf.strings.length(tfstring)

<tf.Tensor: shape=(), dtype=int32, numpy=14>

In [28]:
#decoding string
tf.strings.unicode_decode(tfstring,"UTF8")

<tf.Tensor: shape=(14,), dtype=int32, numpy=
array([ 84, 101, 110, 115, 111, 114, 102, 108, 111, 119,  32,  50,  46,
        48], dtype=int32)>

In [29]:
tfstringarray= tf.constant(["simran","sharma","rahul","suresh"])

In [30]:
for i in tfstringarray:
  print(i)

tf.Tensor(b'simran', shape=(), dtype=string)
tf.Tensor(b'sharma', shape=(), dtype=string)
tf.Tensor(b'rahul', shape=(), dtype=string)
tf.Tensor(b'suresh', shape=(), dtype=string)


In [33]:
for i in tfstringarray:
  print(tf.strings.unicode_decode(i,"UTF8"))
  

tf.Tensor([115 105 109 114  97 110], shape=(6,), dtype=int32)
tf.Tensor([115 104  97 114 109  97], shape=(6,), dtype=int32)
tf.Tensor([114  97 104 117 108], shape=(5,), dtype=int32)
tf.Tensor([115 117 114 101 115 104], shape=(6,), dtype=int32)


In [34]:
for i in tfstringarray:
  print(tf.strings.length(i))

tf.Tensor(6, shape=(), dtype=int32)
tf.Tensor(6, shape=(), dtype=int32)
tf.Tensor(5, shape=(), dtype=int32)
tf.Tensor(6, shape=(), dtype=int32)
